fix failure logging.

diff --git a/conf.d/S70-catch-failure b/conf.d/S70-catch-failure
--- a/conf.d/S70-catch-failure
+++ b/conf.d/S70-catch-failure
@@ -3,18 +3,23 @@
 # use the nice "Command not found" feature from ubuntu
 [ -e /etc/zsh_command_not_found ] && source /etc/zsh_command_not_found
 
-# Prints out a failure notice if things break
-catch_failure()
-{
-    pt=$?
-    if [[ "$pt" != 0 ]]
-    then
-        hist=`history -1 | head -n 1 | sed -e "s/^ *[0-9]* *//"`
-        failure="`history -1 | head -n 1 | sed -e "s/^ *\([0-9]*\) *.*/\1/"`"
-        [[ "$failure" = "$LAST_FAILURE" ]] && return
-        export LAST_FAILURE=$failure
-        echo -e "\033[1;31m'$hist' Failed ($pt)"
-    fi
+
+# track the last executed command _IN THIS SHELL_.
+# Can't just use 'history' or 'fc' because they track across all shells.
+track_exec() {
+    export LAST_EXEC=$2
 }
 
-precmd_functions+='catch_failure'
+preexec_functions+='track_exec'
+
+# Prints out a failure notice if last command failed
+print_failure() {
+    ret_code=$?
+    if [[ "$ret_code" != 0 && -n "$LAST_EXEC" ]]
+    then
+        echo -e "\033[1;31m'$LAST_EXEC' Failed ($ret_code)"
+    fi
+    export LAST_EXEC=
+}
+
+precmd_functions+='print_failure'
